spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petMall?allowPublicKeyRetrieval=true&useSSL=true
    username: root
    password:

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: create-drop
